name: Create Pull Request

on:
  repository_dispatch:
    types: [create_pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CreateFile
        run: |
          rm -rf ${{ github.event.client_payload.path }}
          mkdir -p ${{ github.event.client_payload.path }}
          rm -rf ${{ github.event.client_payload.path }}
          touch ${{ github.event.client_payload.path }}
          echo '${{ github.event.client_payload.file }}' > ${{ github.event.client_payload.path }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Create ${{ github.event.client_payload.path }}
          delete-branch: true
          title: Create ${{ github.event.client_payload.path }}
          branch: create/${{ github.event.client_payload.path }}
