name: Create Pull Request

on:
  repository_dispatch:
    types: [create_pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CreateFile
        run: |
          rm -rf ${{ toJSON(github.event.client_payload).path }}
          touch ${{ toJSON(github.event.client_payload).path }}
          echo "${{ toJSON(github.event.client_payload).file }}" > ${{ toJSON(github.event.client_payload).path }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Create ${{ toJSON(github.event.client_payload).path }}
          delete-branch: true
          title: Create ${{ toJSON(github.event.client_payload).path }}
          branch: create/${{ toJSON(github.event.client_payload).path }}
